# Tomcat????
server:
  port: 8888
spring:
  # ???????
  datasource:
    url: jdbc:mysql://localhost:3306/limebookhouse?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ??jsp
  mvc:
    view:
      # ????????
      prefix: /WEB-INF/jsp/
      # ????????
      suffix: .jsp
    static-path-pattern: /static/**
# mybatis????
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.yhydemo.entity

